import { useReducer, useEffect, useRef, useCallback } from 'react';
import type { WordState, CharState, TypingPhase, EngineResult } from '../types';
import { computeWpm, computeAccuracy } from '../utils/wpm';
function buildWordStates(text: string): WordState[] { return text.trim().split(/\s+/).filter(Boolean).map((word) => ({ word, typed: '', status: 'pending' as const, chars: word.split('').map((char) => ({ char, status: 'pending' as const })) })); }
function chars(word: string, typed: string, active: boolean): CharState[] { const result: CharState[] = []; for (let i = 0; i < Math.max(word.length, typed.length); i++) result.push(i >= word.length ? { char: typed[i], status: 'extra' } : typed[i] === undefined ? { char: word[i], status: active && i === typed.length ? 'current' : 'pending' } : { char: word[i], status: typed[i] === word[i] ? 'correct' : 'error' }); return result; }
function initial(words: WordState[]) { if (words[0]) { words[0].status = 'active'; words[0].chars = chars(words[0].word, '', true); } return words; }
interface State { phase: TypingPhase; wordStates: WordState[]; currentWordIndex: number; currentInput: string; liveWpm: number; liveAccuracy: number; elapsed: number; startTime: number | null; correctWordsCount: number; attemptedWordsCount: number; }
type Action = { type: 'KEY'; key: string; now: number; extend: boolean } | { type: 'TICK'; elapsed: number } | { type: 'FINISH'; elapsed: number } | { type: 'RESET'; words: WordState[] } | { type: 'APPEND'; words: WordState[]; now: number };
const stat = (state: State, elapsed: number) => ({ liveWpm: computeWpm(state.correctWordsCount, elapsed), liveAccuracy: computeAccuracy(state.correctWordsCount, state.attemptedWordsCount) });
function reducer(state: State, action: Action): State {
  if (action.type === 'RESET') return { phase: 'idle', wordStates: action.words, currentWordIndex: 0, currentInput: '', liveWpm: 0, liveAccuracy: 100, elapsed: 0, startTime: null, correctWordsCount: 0, attemptedWordsCount: 0 };
  if (action.type === 'APPEND') { if (!action.words.length) return state; const wordStates = [...state.wordStates, ...action.words]; if (state.currentWordIndex >= state.wordStates.length) { const next = { ...wordStates[state.currentWordIndex], status: 'active' as const, startTime: action.now }; next.chars = chars(next.word, '', true); wordStates[state.currentWordIndex] = next; } return { ...state, wordStates }; }
  if (action.type === 'TICK') return state.phase === 'running' ? { ...state, elapsed: action.elapsed, ...stat(state, action.elapsed) } : state;
  if (action.type === 'FINISH') return state.phase === 'finished' ? state : { ...state, phase: 'finished', elapsed: action.elapsed, ...stat(state, action.elapsed) };
  if (state.phase === 'finished' || !state.wordStates[state.currentWordIndex]) return state;
  const now = action.now; const startTime = state.startTime ?? now; const phase: TypingPhase = state.phase === 'idle' ? 'running' : state.phase; const elapsed = (now - startTime) / 1000;
  if (action.key === 'Backspace') { if (!state.currentInput) return { ...state, phase, startTime }; const currentInput = state.currentInput.slice(0, -1); const wordStates = [...state.wordStates]; const word = { ...wordStates[state.currentWordIndex], typed: currentInput }; word.chars = chars(word.word, currentInput, true); wordStates[state.currentWordIndex] = word; return { ...state, phase, startTime, currentInput, wordStates, elapsed, ...stat(state, elapsed) }; }
  const commit = (input: string): State => { if (!input) return { ...state, phase, startTime }; const wordStates = [...state.wordStates]; const completed = { ...wordStates[state.currentWordIndex] }; const correct = completed.word === input; completed.typed = input; completed.status = correct ? 'correct' : 'error'; completed.timeTakenMs = completed.startTime ? now - completed.startTime : 0; completed.chars = chars(completed.word, input, false); wordStates[state.currentWordIndex] = completed; const correctWordsCount = state.correctWordsCount + (correct ? 1 : 0); const attemptedWordsCount = state.attemptedWordsCount + 1; const nextIndex = state.currentWordIndex + 1; const next = { ...state, phase, startTime, wordStates, currentWordIndex: nextIndex, currentInput: '', correctWordsCount, attemptedWordsCount, elapsed }; if (nextIndex >= wordStates.length) return action.extend ? { ...next, ...stat(next, elapsed) } : { ...next, phase: 'finished' as TypingPhase, ...stat(next, elapsed) }; const active = { ...wordStates[nextIndex], status: 'active' as const, startTime: now }; active.chars = chars(active.word, '', true); wordStates[nextIndex] = active; return { ...next, ...stat(next, elapsed) }; };
  if (action.key === ' ') return commit(state.currentInput); if (action.key.length !== 1) return state;
  const currentInput = state.currentInput + action.key; const wordStates = [...state.wordStates]; const active = { ...wordStates[state.currentWordIndex], status: 'active' as const, startTime: wordStates[state.currentWordIndex].startTime ?? now, typed: currentInput }; active.chars = chars(active.word, currentInput, true); wordStates[state.currentWordIndex] = active;
  if (state.currentWordIndex === wordStates.length - 1 && currentInput === active.word) return commit(currentInput);
  const next = { ...state, phase, startTime, currentInput, wordStates, elapsed }; return { ...next, ...stat(next, elapsed) };
}
interface Options { text: string; durationSeconds: number; onComplete: (result: EngineResult) => void; extendContent?: boolean; }
interface Return { phase: TypingPhase; wordStates: WordState[]; currentWordIndex: number; liveWpm: number; liveAccuracy: number; elapsed: number; remaining: number; resetEngine: (text?: string) => void; appendText: (text: string) => void; }
export function useTypingEngine({ text, durationSeconds, onComplete, extendContent = false }: Options): Return {
  const [state, dispatch] = useReducer(reducer, undefined, () => ({ phase: 'idle' as TypingPhase, wordStates: initial(buildWordStates(text)), currentWordIndex: 0, currentInput: '', liveWpm: 0, liveAccuracy: 100, elapsed: 0, startTime: null, correctWordsCount: 0, attemptedWordsCount: 0 })); const ref = useRef(state); ref.current = state; const done = useRef(onComplete); done.current = onComplete; const duration = useRef(durationSeconds); duration.current = durationSeconds; const previous = useRef(text); const extend = useRef(extendContent); extend.current = extendContent;
  useEffect(() => { if (text !== previous.current) { previous.current = text; handled.current = false; dispatch({ type: 'RESET', words: initial(buildWordStates(text)) }); } }, [text]);
  useEffect(() => { if (state.phase !== 'running' || !state.startTime) return; const id = window.setInterval(() => { const elapsed = (Date.now() - ref.current.startTime!) / 1000; dispatch(elapsed >= duration.current ? { type: 'FINISH', elapsed: duration.current } : { type: 'TICK', elapsed }); }, 100); return () => window.clearInterval(id); }, [state.phase, state.startTime]);
  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.ctrlKey || event.metaKey || event.altKey || event.key === 'Tab') return; if (event.key === ' ' || event.key === 'Backspace') event.preventDefault(); dispatch({ type: 'KEY', key: event.key, now: Date.now(), extend: extend.current }); }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); }, []);
  const handled = useRef(false); useEffect(() => { if (state.phase !== 'finished' || handled.current) return; handled.current = true; const completed = state.wordStates.filter((word) => word.status === 'correct' || word.status === 'error').map((word) => ({ word: word.word, typed: word.typed, correct: word.word === word.typed, timeTakenMs: word.timeTakenMs ?? 0 })); const active = state.wordStates[state.currentWordIndex]; if (active?.status === 'active' && state.currentInput) completed.push({ word: active.word, typed: state.currentInput, correct: false, timeTakenMs: 0 }); const start = state.startTime ?? Date.now(); done.current({ typedWords: completed, durationSeconds: state.elapsed, startTime: new Date(start).toISOString(), endTime: new Date(start + state.elapsed * 1000).toISOString(), clientWpm: computeWpm(completed.filter((word) => word.correct).length, state.elapsed), clientAccuracy: computeAccuracy(completed.filter((word) => word.correct).length, completed.length) }); }, [state]);
  const resetEngine = useCallback((nextText?: string) => { handled.current = false; dispatch({ type: 'RESET', words: initial(buildWordStates(nextText ?? text)) }); }, [text]); const appendText = useCallback((nextText: string) => dispatch({ type: 'APPEND', words: buildWordStates(nextText), now: Date.now() }), []);
  return { phase: state.phase, wordStates: state.wordStates, currentWordIndex: state.currentWordIndex, liveWpm: state.liveWpm, liveAccuracy: state.liveAccuracy, elapsed: state.elapsed, remaining: Math.max(0, durationSeconds - state.elapsed), resetEngine, appendText };
}