/**
 * Canonical typing-test paragraph pool: a large set of unique, meaningful
 * English paragraphs used by the typing challenge. Challenge text is built by
 * sampling from this pool WITHOUT repeats within a single challenge, so the
 * pool must stay big enough to cover the longest duration across several
 * rematch rounds.
 *
 * Tuple order: [difficulty, topic, content]. Content must be unique — both
 * seed scripts upsert/insert by content, and the challenge text builder
 * relies on every paragraph being distinct.
 */
export const PARAGRAPHS: Array<[string, string, string]> = [
  // ---- beginner ----
  ['beginner', 'nature', 'The sun came up over the hill. A bird sang in the tree. The grass was wet with dew.'],
  ['beginner', 'cooking', 'Maya put the apples in a blue bowl. She cut them into small pieces. Her brother added a pinch of sugar and they shared a snack.'],
  ['beginner', 'travel', 'The small train left the town at dawn. It went past the river and the hills. The day was calm and clear.'],
  ['beginner', 'reading', 'Sam sat by the window with a book. He read about space and stars. The rain fell soft on the road outside.'],
  ['beginner', 'sports', 'Our team ran short passes after school. By sunset, everyone could move the ball well. The coach smiled at the end.'],
  ['beginner', 'pets', 'The puppy sat by the door before every walk. A gentle pat and a kind word made him very happy.'],
  ['beginner', 'weather', 'Clouds came over the town in the afternoon. Then rain washed the road. The sky cleared by night.'],
  ['beginner', 'music', 'Lena played a soft tune on the piano. Her hands moved slow at first. Soon she found the song.'],
  ['beginner', 'school', 'The class put bean seeds in clear cups. Each day they measured the stems. They wrote down what they saw.'],
  ['beginner', 'community', 'Neighbors met at the park to pick up trash. They painted the old benches. The path looked clean and new.'],
  ['beginner', 'market', 'A farmer set out bright carrots on a wooden table. He added tomatoes and lettuce. Shoppers asked where the food was grown.'],
  ['beginner', 'friendship', 'Two friends made a paper kite from sticks and paper. When the wind rose they ran across the field.'],
  ['beginner', 'science', 'Ice melts when it gets heat. The water can freeze again if it gets cold.'],
  ['beginner', 'home', 'Dad fixed the loose drawer by the sink. He used a small tool. Then the kitchen looked clean and neat.'],
  ['beginner', 'art', 'The art club used wide brushes to paint a sunset. Orange and pink filled the paper. The picture hung on the wall.'],
  ['beginner', 'baking', 'The fresh bread came out of the oven. The kitchen smelled warm and sweet. Everyone gathered around the table.'],
  ['beginner', 'garden', 'Nina watered the tomato plants every evening. The leaves turned deep green. Soon tiny fruit began to form.'],
  ['beginner', 'lake', 'We packed a small boat and rowed to the far side of the lake. The water was still and the sky was wide.'],
  ['beginner', 'dinner', 'Dinner was ready at six. We set four plates on the table. Then we talked about our day.'],
  ['beginner', 'library', 'The library stays open until nine on weekdays. Rows of shelves hold books on every subject. The back room is always quiet.'],
  ['beginner', 'coffee', 'The morning coffee was hot and strong. Steam rose from the dark cup. A soft light came through the window.'],
  ['beginner', 'cycling', 'The bike path winds through the park and along the river. It is smooth and wide. Many families ride there at sunset.'],
  ['beginner', 'stars', 'We counted stars from the back porch. The city lights were far away. The sky felt deep and wide.'],
  ['beginner', 'fishing', 'Grandpa baited the hooks and cast his line. The float bobbed gently. We waited in the quiet afternoon.'],
  ['beginner', 'teahouse', 'The teahouse serves warm tea with little cakes. The tables sit by the big window. Rain taps soft on the glass.'],
  ['beginner', 'kite', 'The red kite climbed high above the field. The string hummed in the wind. We let it fly until dusk.'],
  ['beginner', 'harvest', 'The farm stands open on Saturday mornings. Apples fill the wooden crates. A wagon of pumpkins sits by the road.'],
  ['beginner', 'postcard', 'She sent a postcard from the coast. It showed a lighthouse and the sea. The note inside was short and kind.'],
  ['beginner', 'puzzle', 'We poured the pieces onto the big table. The edge was easy first. The center took the whole week.'],
  ['beginner', 'bus', 'The bus leaves the square at half past seven. The morning ride is quick. The best seat is by the window.'],
  ['beginner', 'camping', 'The tent stood near the pines. We cooked dinner over a small fire. The forest fell quiet after dark.'],
  ['beginner', 'shop', 'The corner shop opens at eight. It sells milk, bread, and fresh fruit. The owner knows most names.'],
  ['beginner', 'guitar', 'The old guitar has six worn strings. She practiced the same chord again. Each time the sound grew softer and rounder.'],
  ['beginner', 'swimming', 'The pool is clean and warm. Lanes run along the far wall. Swimmers move in steady rhythm.'],
  ['beginner', 'morning', 'The morning light spread across the floor. A cup of tea cooled on the sill. The day had not started yet.'],
  ['beginner', 'pottery', 'The clay was cool against her hands. She pressed and shaped the bowl slowly. Tiny cracks smoothed away with water.'],
  // ---- intermediate ----
  ['intermediate', 'history', 'Before maps fit inside a phone, sailors relied on stars, compasses, and careful notes. Their journals recorded winds, currents, and landmarks that helped later voyages.'],
  ['intermediate', 'technology', 'A good password is long, unique, and difficult to guess. Password managers make this easier by storing strong credentials without asking people to remember every detail.'],
  ['intermediate', 'health', 'Regular movement improves more than strength. A short walk can clear the mind, support sleep, and create a useful break between demanding tasks.'],
  ['intermediate', 'architecture', 'The bridge uses a pattern of triangles because that shape spreads weight efficiently. Engineers tested the design with models long before construction began.'],
  ['intermediate', 'ocean', 'Coral reefs shelter a remarkable variety of life, yet they are sensitive to warmer water and pollution. Protecting nearby coastlines helps reefs recover after storms.'],
  ['intermediate', 'economics', 'When a local bakery buys flour from a nearby mill, money circulates through several small businesses. Those connections can make a neighborhood more resilient.'],
  ['intermediate', 'language', 'Languages change whenever people borrow ideas, invent tools, or move to new places. Dictionaries describe this change; they do not stop it.'],
  ['intermediate', 'photography', 'Good photographs often depend on patience rather than expensive equipment. Waiting for a cloud to shift can transform ordinary light into something memorable.'],
  ['intermediate', 'gardening', 'Compost turns kitchen scraps and fallen leaves into rich soil over time. The process requires air, moisture, and a balance of green and brown material.'],
  ['intermediate', 'energy', 'Solar panels produce electricity when light reaches their cells, even on many cloudy days. Batteries can store some of that energy for use after sunset.'],
  ['intermediate', 'writing', 'Clear writing begins with a clear purpose. Once a reader understands the main point, examples and details can guide them through the rest of the argument.'],
  ['intermediate', 'wildlife', 'Beavers reshape streams by building dams from branches and mud. The ponds they create provide habitat for fish, birds, insects, and amphibians.'],
  ['intermediate', 'medicine', 'Vaccines train the immune system to recognize a threat before the real infection appears. This preparation can reduce the chance of severe illness.'],
  ['intermediate', 'business', 'A useful meeting ends with decisions, owners, and dates. Without those three things, even an energetic discussion can fade into a list of unfinished ideas.'],
  ['intermediate', 'astronomy', 'Telescopes collect faint light that human eyes cannot see alone. By studying that light, astronomers estimate the distance, motion, and composition of distant objects.'],
  ['intermediate', 'geography', 'Rivers rarely follow a straight line. They bend around stubborn ground, carve new paths after floods, and slowly move sediment from the highlands toward the sea.'],
  ['intermediate', 'weather', 'Thunderstorms form when warm, moist air rises and cools quickly. The height of the cloud matters more than its width, and the heaviest rain usually falls near the leading edge.'],
  ['intermediate', 'community', 'A community garden does more than grow vegetables. Shared plots bring neighbors together, reduce food costs, and turn unused land into a place people actually visit.'],
  ['intermediate', 'books', 'Reading builds vocabulary slowly but steadily. Every unfamiliar word appears in context, so meaning comes from the sentence rather than from a memorized list.'],
  ['intermediate', 'cooking', 'Cooking well is mostly a matter of timing rather than talent. Ingredients that look similar behave differently, and a few minutes can change a dish more than any spice.'],
  ['intermediate', 'fitness', 'Consistency beats intensity for most fitness goals. A modest routine repeated three times a week usually outperforms a punishing workout attempted once a month.'],
  ['intermediate', 'birds', 'Migrating birds navigate using the sun, the stars, and even Earth\'s magnetic field. Some species cover thousands of miles, stopping only when weather turns dangerous.'],
  ['intermediate', 'water', 'Fresh water is limited even though the planet looks blue. Most of it sits frozen or underground, which is why rivers, lakes, and aquifers require careful management.'],
  ['intermediate', 'forests', 'A healthy forest stores carbon and moderates local temperature. Trees draw moisture from the soil and release it slowly, shading the ground and cooling the air around them.'],
  ['intermediate', 'transport', 'Public transit works best when it connects frequent hubs with short waits. A reliable fifteen-minute service often attracts more riders than a faster line that runs hourly.'],
  ['intermediate', 'sleep', 'Sleep is when the brain consolidates memory and clears the day\'s signaling clutter. Missing a single night impairs focus more than most people expect.'],
  ['intermediate', 'soil', 'Soil is not inert dirt; it teems with organisms that recycle nutrients. When compaction kills that activity, fertilizer alone rarely restores a field.'],
  ['intermediate', 'market', 'Farmers\' markets reward local variety. Produce picked the same morning travels the shortest distance, so it can ripen naturally instead of being harvested early for shipping.'],
  ['intermediate', 'museum', 'A museum tells many stories with a single object. Curators choose labels carefully because the words beside an artifact shape how visitors read its meaning.'],
  ['intermediate', 'maps', 'Every map distorts something because a sphere cannot flatten into a rectangle without change. Cartographers decide which shapes, distances, or areas matter most for a given use.'],
  ['intermediate', 'sound', 'Sound travels slower than light, which is why thunder follows lightning. The delay between flash and boom gives a rough estimate of how far away a storm sits.'],
  ['intermediate', 'farming', 'Crop rotation keeps soil productive without heavy chemical use. Different plants take and return different nutrients, so alternating them can disrupt the cycles of pests.'],
  ['intermediate', 'trail', 'Well-designed trails use gentle grades and switchbacks so hikers climb steadily without erosion. Drainage cuts keep rainwater off the path and out of the stream.'],
  ['intermediate', 'porcelain', 'Porcelain reaches strength through very high firing temperatures. The clay fuses into a smooth, dense body that resists water far better than ordinary earthenware.'],
  ['intermediate', 'library', 'Public libraries lend far more than books. Many also provide internet access, workspaces, and classes, which makes them quiet anchors of civic life in larger cities.'],
  ['intermediate', 'coins', 'Coins circulate longer than paper money because metal survives handling. Their wear reveals how often a design passes through hands before returning to the bank.'],
  // ---- advanced ----
  ['advanced', 'climate', 'Climate models do not predict one inevitable future; they compare plausible futures under different assumptions. Their value lies in showing how choices about emissions, land use, and energy can alter long-term risks.'],
  ['advanced', 'psychology', 'Attention is not simply a spotlight that can be aimed without cost. Each interruption imposes a small rebuilding period, which is why sustained work often benefits from deliberate boundaries.'],
  ['advanced', 'law', 'The rule of law depends on procedures being applied consistently, including when the outcome is inconvenient. Public confidence weakens when similar cases appear to receive different standards.'],
  ['advanced', 'biology', 'Evolution is not a ladder of progress but a branching process shaped by selection, chance, and changing environments. Traits persist when they improve reproduction in a particular context.'],
  ['advanced', 'design', 'Accessible design treats variation as ordinary rather than exceptional. Captions, contrast, keyboard navigation, and clear language usually improve an experience for everyone, not only for a narrow group.'],
  ['advanced', 'philosophy', 'A difficult question is not made less important by lacking a quick answer. Careful reasoning can clarify which values are in conflict and what each possible choice would require.'],
  ['advanced', 'computing', 'Distributed systems trade simplicity for resilience. When information is copied across machines, designers must decide how the system behaves while those machines briefly disagree.'],
  ['advanced', 'urbanism', 'A city street serves more than cars moving through it. Sidewalks, trees, transit stops, storefronts, and safe crossings determine whether people can use the space comfortably throughout the day.'],
  ['advanced', 'statistics', 'An average can conceal important differences inside a group. Looking at the distribution, the sample size, and the method of collection often reveals whether a simple summary is misleading.'],
  ['advanced', 'ethics', 'Automation can make a decision faster without making it fairer. Responsible systems identify who bears the cost of mistakes and provide a meaningful way to question an outcome.'],
  ['advanced', 'geology', 'A mountain range records collisions that occurred over millions of years. Folded layers, mineral changes, and displaced faults preserve evidence of pressure far below the present landscape.'],
  ['advanced', 'education', 'Memorization has a role, but durable learning requires retrieval, feedback, and application. Students understand an idea more deeply when they must use it in an unfamiliar setting.'],
  ['advanced', 'economics', 'Prices communicate information, yet they do not capture every consequence of a decision. Clean air, unpaid care, and future damage may be absent from a transaction even when they matter greatly.'],
  ['advanced', 'security', 'Security is a practice of reducing risk, not a promise of perfect safety. Layered defenses, timely updates, and honest incident reviews make failures less likely and less damaging.'],
  ['advanced', 'art', 'A compelling story balances expectation with surprise. Readers need enough structure to follow the path, but enough uncertainty to feel that the next turn matters.'],
  ['advanced', 'ecology', 'Ecosystems rarely move toward a single stable endpoint; they shift with disturbance, recovery, and seasonal rhythms. Management that tolerates change often preserves more diversity than rigid control.'],
  ['advanced', 'linguistics', 'Language acquisition is not pure imitation. Children generate structures they have never heard, evidence that minds actively build grammatical rules from uneven and incomplete input.'],
  ['advanced', 'sociology', 'Trust is both personal and structural. Institutions earn confidence through predictable, visible procedures, while individuals extend trust based on repeated interaction and shared norms.'],
  ['advanced', 'networks', 'Networks reveal their character under stress. When a few nodes carry most traffic, removing them can fragment the whole system, so resilient designs distribute load and keep redundant paths.'],
  ['advanced', 'medicine', 'Diagnostic reasoning weighs the cost of missing a rare disease against the cost of chasing it. Physicians order tests when the result would change treatment, not merely to exhaust possibilities.'],
  ['advanced', 'history', 'Historical records are never transparent; they are produced by people with motives, audiences, and blind spots. Reading across conflicting sources is often closer to the truth than trusting a single account.'],
  ['advanced', 'physics', 'Observations are theory-laden: what an experiment reveals depends on the instruments and assumptions framing it. Refinement happens when results clash with expectations in ways instruments make visible.'],
  ['advanced', 'negotiation', 'Strong negotiators separate positions from interests. By identifying the need behind a demand, parties can invent options that satisfy both sides instead of haggling over a fixed amount.'],
  ['advanced', 'journalism', 'Reporting stakes its credibility on verification. A story that declines a dramatic rumor because it cannot be checked preserves trust better than a scoop that later unravels in public.'],
  ['advanced', 'ethics', 'Trade-offs are easiest to ignore when the harmed party is distant. Responsible systems make consequences visible, so decision-makers cannot claim ignorance of effects that merely occurred elsewhere.'],
  ['advanced', 'conservation', 'Protected areas work best when they connect rather than isolate. Corridors let species move with the seasons, and local communities often become stronger stewards when they share the benefits.'],
  ['advanced', 'data', 'Visualization is an argument, not a neutral display. Axis choices, color, and aggregation all steer interpretation, which is why the same dataset can support opposite conclusions in print.'],
  ['advanced', 'robotics', 'Robots in human spaces succeed by predictable behavior more than raw capability. People form accurate expectations quickly, and surprise, no matter how clever, erodes that confidence.'],
  ['advanced', 'cognition', 'Expertise looks effortless because it is pattern recognition on top of stored experience. The expert has seen the situation before in enough variations to act without deliberating.'],
  ['advanced', 'urbanplanning', 'Walkability clusters services within short distances and keeps sidewalks continuous. When essential trips become walking trips, streets grow calmer, safer, and more economically diverse.'],
];